version: "3.9"
services:
  rss-bridge:
    image: rssbridge/rss-bridge:latest
    container_name: rss-reader-telegram-bot-rss-bridge
    volumes:
      - ./rss-bridge/config:/config
    restart: unless-stopped
  mongo-db:
    image: mongo:4.4
    container_name: rss-reader-telegram-bot-mongo-db
    volumes:
      - ./mongo-db/data:/data/db
    restart: unless-stopped
  telegram-bot:
    image: rss-reader-telegram-bot:latest
    build: ./rss-reader-telegram-bot/source-code/
    container_name: rss-reader-telegram-bot-telegram-bot
    volumes:
      - ./rss-reader-telegram-bot/config:/config
    restart: unless-stopped
    env_file:
      - ./rss-reader-telegram-bot/.env
    environment:
      - DATABASE_DB_HOST=mongo-db
      - RSS_FEEDS_YAML_FILENAME=/config/custom_feeds.yaml
networks:
  default:
    name: rss-reader-telegram-bot-network
    driver: bridge

