version: "3.9"
services:
  rss-bridge:
    image: rssbridge/rss-bridge:latest
    container_name: rss-reader-telegram-bot-rss-bridge
    volumes:
      - ./rss-bridge/config:/config
    ports:
      - 5001:80
    restart: unless-stopped
  rss-hub:
    image: diygod/rsshub:latest
    container_name: rss-reader-telegram-bot-rss-hub
    ports:
      - 5002:1200
    restart: unless-stopped
    env_file:
      - ./rss-hub/.env
  mongo-db:
    image: mongo:4.4
    container_name: rss-reader-telegram-bot-mongo-db
    volumes:
      - ./mongo-db/data:/data/db
    ports:
      - 5003:27017
    restart: unless-stopped
  telegram-bot:
    image: rss-reader-telegram-bot:latest
    build: ./telegram-bot/source-code/
    container_name: rss-reader-telegram-bot-telegram-bot
    volumes:
      - ./telegram-bot/config:/config
    restart: unless-stopped
    env_file:
      - ./telegram-bot/.env
    environment:
      - DATABASE_DB_HOST=mongo-db
      - RSS_FEEDS_YAML_FILENAME=/config/custom_feeds.yaml
      - LOGGING_LOG_PATH=/config/bot.log
networks:
  default:
    name: rss-reader-telegram-bot-network
    driver: bridge
