name: Update all git submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    name: Update all git submodules
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout with submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.UPDATE_SUBMODULES_ACTION_TOKEN }}
          submodules: true
      - name: Pull & update submodules recursively
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update submodules"
          git push
